export const dummyData = {
  relatedLinks: [
    {
      fixslug: "test-engine-oil-leak-to-diagnose",
      fixslugpath: "/fixes/test-engine-oil-leak-to-diagnose",
      _title: "Test Engine Oil Leak To Diagnose",
      _full_title: "",
    },
    {
      fixslug: "oil-pressure-sensor-replacement",
      fixslugpath: "/fixes/oil-pressure-sensor-replacement",
      _title: "Oil Pressure Sensor Replacement",
      _full_title: "",
    },
    {
      fixslug: "transmission-output-shaft-seal-replacement",
      fixslugpath: "/fixes/transmission-output-shaft-seal-replacement",
      _title: "Transmission Output Shaft Seal Replacement",
      _full_title: "",
    },
    {
      fixslug: "brake-vacuum-pump-replacement",
      fixslugpath: "/fixes/brake-vacuum-pump-replacement",
      _title: "Brake Vacuum Pump Replacement",
      _full_title: "",
    },
    {
      fixslug: "oil-cooler-line-replacement",
      fixslugpath: "/fixes/oil-cooler-line-replacement",
      _title: "Oil Cooler Line Replacement",
      _full_title: "",
    },
    {
      fixslug: "",
      fixslugpath: "/fixes/",
      _title: "",
      _full_title: "",
    },
  ],

  allStateLinks: [
    {
      state_id: "AK",
      state_name: "Alaska",
      fixslug: "transaxle-output-shaft-seal-replacement-in-alaska",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-alaska",
      _title: "Transaxle Output Shaft Seal Replacement in Alaska",
    },
    {
      state_id: "AL",
      state_name: "Alabama",
      fixslug: "transaxle-output-shaft-seal-replacement-in-alabama",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-alabama",
      _title: "Transaxle Output Shaft Seal Replacement in Alabama",
    },
    {
      state_id: "AR",
      state_name: "Arkansas",
      fixslug: "transaxle-output-shaft-seal-replacement-in-arkansas",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-arkansas",
      _title: "Transaxle Output Shaft Seal Replacement in Arkansas",
    },
    {
      state_id: "AZ",
      state_name: "Arizona",
      fixslug: "transaxle-output-shaft-seal-replacement-in-arizona",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-arizona",
      _title: "Transaxle Output Shaft Seal Replacement in Arizona",
    },
    {
      state_id: "CA",
      state_name: "California",
      fixslug: "transaxle-output-shaft-seal-replacement-in-california",
      fixslugpath:
        "/fixes/transaxle-output-shaft-seal-replacement-in-california",
      _title: "Transaxle Output Shaft Seal Replacement in California",
    },
    {
      state_id: "CO",
      state_name: "Colorado",
      fixslug: "transaxle-output-shaft-seal-replacement-in-colorado",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-colorado",
      _title: "Transaxle Output Shaft Seal Replacement in Colorado",
    },
    {
      state_id: "CT",
      state_name: "Connecticut",
      fixslug: "transaxle-output-shaft-seal-replacement-in-connecticut",
      fixslugpath:
        "/fixes/transaxle-output-shaft-seal-replacement-in-connecticut",
      _title: "Transaxle Output Shaft Seal Replacement in Connecticut",
    },
    {
      state_id: "DC",
      state_name: "District of Columbia",
      fixslug:
        "transaxle-output-shaft-seal-replacement-in-district-of-columbia",
      fixslugpath:
        "/fixes/transaxle-output-shaft-seal-replacement-in-district-of-columbia",
      _title: "Transaxle Output Shaft Seal Replacement in District of Columbia",
    },
    {
      state_id: "DE",
      state_name: "Delaware",
      fixslug: "transaxle-output-shaft-seal-replacement-in-delaware",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-delaware",
      _title: "Transaxle Output Shaft Seal Replacement in Delaware",
    },
    {
      state_id: "FL",
      state_name: "Florida",
      fixslug: "transaxle-output-shaft-seal-replacement-in-florida",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-florida",
      _title: "Transaxle Output Shaft Seal Replacement in Florida",
    },
    {
      state_id: "GA",
      state_name: "Georgia",
      fixslug: "transaxle-output-shaft-seal-replacement-in-georgia",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-georgia",
      _title: "Transaxle Output Shaft Seal Replacement in Georgia",
    },
    {
      state_id: "HI",
      state_name: "Hawaii",
      fixslug: "transaxle-output-shaft-seal-replacement-in-hawaii",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-hawaii",
      _title: "Transaxle Output Shaft Seal Replacement in Hawaii",
    },
    {
      state_id: "IA",
      state_name: "Iowa",
      fixslug: "transaxle-output-shaft-seal-replacement-in-iowa",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-iowa",
      _title: "Transaxle Output Shaft Seal Replacement in Iowa",
    },
    {
      state_id: "ID",
      state_name: "Idaho",
      fixslug: "transaxle-output-shaft-seal-replacement-in-idaho",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-idaho",
      _title: "Transaxle Output Shaft Seal Replacement in Idaho",
    },
    {
      state_id: "IL",
      state_name: "Illinois",
      fixslug: "transaxle-output-shaft-seal-replacement-in-illinois",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-illinois",
      _title: "Transaxle Output Shaft Seal Replacement in Illinois",
    },
    {
      state_id: "IN",
      state_name: "Indiana",
      fixslug: "transaxle-output-shaft-seal-replacement-in-indiana",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-indiana",
      _title: "Transaxle Output Shaft Seal Replacement in Indiana",
    },
    {
      state_id: "KS",
      state_name: "Kansas",
      fixslug: "transaxle-output-shaft-seal-replacement-in-kansas",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-kansas",
      _title: "Transaxle Output Shaft Seal Replacement in Kansas",
    },
    {
      state_id: "KY",
      state_name: "Kentucky",
      fixslug: "transaxle-output-shaft-seal-replacement-in-kentucky",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-kentucky",
      _title: "Transaxle Output Shaft Seal Replacement in Kentucky",
    },
    {
      state_id: "LA",
      state_name: "Louisiana",
      fixslug: "transaxle-output-shaft-seal-replacement-in-louisiana",
      fixslugpath:
        "/fixes/transaxle-output-shaft-seal-replacement-in-louisiana",
      _title: "Transaxle Output Shaft Seal Replacement in Louisiana",
    },
    {
      state_id: "MA",
      state_name: "Massachusetts",
      fixslug: "transaxle-output-shaft-seal-replacement-in-massachusetts",
      fixslugpath:
        "/fixes/transaxle-output-shaft-seal-replacement-in-massachusetts",
      _title: "Transaxle Output Shaft Seal Replacement in Massachusetts",
    },
    {
      state_id: "MD",
      state_name: "Maryland",
      fixslug: "transaxle-output-shaft-seal-replacement-in-maryland",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-maryland",
      _title: "Transaxle Output Shaft Seal Replacement in Maryland",
    },
    {
      state_id: "ME",
      state_name: "Maine",
      fixslug: "transaxle-output-shaft-seal-replacement-in-maine",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-maine",
      _title: "Transaxle Output Shaft Seal Replacement in Maine",
    },
    {
      state_id: "MI",
      state_name: "Michigan",
      fixslug: "transaxle-output-shaft-seal-replacement-in-michigan",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-michigan",
      _title: "Transaxle Output Shaft Seal Replacement in Michigan",
    },
    {
      state_id: "MN",
      state_name: "Minnesota",
      fixslug: "transaxle-output-shaft-seal-replacement-in-minnesota",
      fixslugpath:
        "/fixes/transaxle-output-shaft-seal-replacement-in-minnesota",
      _title: "Transaxle Output Shaft Seal Replacement in Minnesota",
    },
    {
      state_id: "MO",
      state_name: "Missouri",
      fixslug: "transaxle-output-shaft-seal-replacement-in-missouri",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-missouri",
      _title: "Transaxle Output Shaft Seal Replacement in Missouri",
    },
    {
      state_id: "MS",
      state_name: "Mississippi",
      fixslug: "transaxle-output-shaft-seal-replacement-in-mississippi",
      fixslugpath:
        "/fixes/transaxle-output-shaft-seal-replacement-in-mississippi",
      _title: "Transaxle Output Shaft Seal Replacement in Mississippi",
    },
    {
      state_id: "MT",
      state_name: "Montana",
      fixslug: "transaxle-output-shaft-seal-replacement-in-montana",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-montana",
      _title: "Transaxle Output Shaft Seal Replacement in Montana",
    },
    {
      state_id: "NC",
      state_name: "North Carolina",
      fixslug: "transaxle-output-shaft-seal-replacement-in-north-carolina",
      fixslugpath:
        "/fixes/transaxle-output-shaft-seal-replacement-in-north-carolina",
      _title: "Transaxle Output Shaft Seal Replacement in North Carolina",
    },
    {
      state_id: "ND",
      state_name: "North Dakota",
      fixslug: "transaxle-output-shaft-seal-replacement-in-north-dakota",
      fixslugpath:
        "/fixes/transaxle-output-shaft-seal-replacement-in-north-dakota",
      _title: "Transaxle Output Shaft Seal Replacement in North Dakota",
    },
    {
      state_id: "NE",
      state_name: "Nebraska",
      fixslug: "transaxle-output-shaft-seal-replacement-in-nebraska",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-nebraska",
      _title: "Transaxle Output Shaft Seal Replacement in Nebraska",
    },
    {
      state_id: "NH",
      state_name: "New Hampshire",
      fixslug: "transaxle-output-shaft-seal-replacement-in-new-hampshire",
      fixslugpath:
        "/fixes/transaxle-output-shaft-seal-replacement-in-new-hampshire",
      _title: "Transaxle Output Shaft Seal Replacement in New Hampshire",
    },
    {
      state_id: "NJ",
      state_name: "New Jersey",
      fixslug: "transaxle-output-shaft-seal-replacement-in-new-jersey",
      fixslugpath:
        "/fixes/transaxle-output-shaft-seal-replacement-in-new-jersey",
      _title: "Transaxle Output Shaft Seal Replacement in New Jersey",
    },
    {
      state_id: "NM",
      state_name: "New Mexico",
      fixslug: "transaxle-output-shaft-seal-replacement-in-new-mexico",
      fixslugpath:
        "/fixes/transaxle-output-shaft-seal-replacement-in-new-mexico",
      _title: "Transaxle Output Shaft Seal Replacement in New Mexico",
    },
    {
      state_id: "NV",
      state_name: "Nevada",
      fixslug: "transaxle-output-shaft-seal-replacement-in-nevada",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-nevada",
      _title: "Transaxle Output Shaft Seal Replacement in Nevada",
    },
    {
      state_id: "NY",
      state_name: "New York",
      fixslug: "transaxle-output-shaft-seal-replacement-in-new-york",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-new-york",
      _title: "Transaxle Output Shaft Seal Replacement in New York",
    },
    {
      state_id: "OH",
      state_name: "Ohio",
      fixslug: "transaxle-output-shaft-seal-replacement-in-ohio",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-ohio",
      _title: "Transaxle Output Shaft Seal Replacement in Ohio",
    },
    {
      state_id: "OK",
      state_name: "Oklahoma",
      fixslug: "transaxle-output-shaft-seal-replacement-in-oklahoma",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-oklahoma",
      _title: "Transaxle Output Shaft Seal Replacement in Oklahoma",
    },
    {
      state_id: "OR",
      state_name: "Oregon",
      fixslug: "transaxle-output-shaft-seal-replacement-in-oregon",
      _title: "Transaxle Output Shaft Seal Replacement in Oregon",
    },
    {
      state_id: "PA",
      state_name: "Pennsylvania",
      fixslug: "transaxle-output-shaft-seal-replacement-in-pennsylvania",
      fixslugpath:
        "/fixes/transaxle-output-shaft-seal-replacement-in-pennsylvania",
      _title: "Transaxle Output Shaft Seal Replacement in Pennsylvania",
    },
    {
      state_id: "RI",
      state_name: "Rhode Island",
      fixslug: "transaxle-output-shaft-seal-replacement-in-rhode-island",
      fixslugpath:
        "/fixes/transaxle-output-shaft-seal-replacement-in-rhode-island",
      _title: "Transaxle Output Shaft Seal Replacement in Rhode Island",
    },
    {
      state_id: "SC",
      state_name: "South Carolina",
      fixslug: "transaxle-output-shaft-seal-replacement-in-south-carolina",
      fixslugpath:
        "/fixes/transaxle-output-shaft-seal-replacement-in-south-carolina",
      _title: "Transaxle Output Shaft Seal Replacement in South Carolina",
    },
    {
      state_id: "SD",
      state_name: "South Dakota",
      fixslug: "transaxle-output-shaft-seal-replacement-in-south-dakota",
      fixslugpath:
        "/fixes/transaxle-output-shaft-seal-replacement-in-south-dakota",
      _title: "Transaxle Output Shaft Seal Replacement in South Dakota",
    },
    {
      state_id: "TN",
      state_name: "Tennessee",
      fixslug: "transaxle-output-shaft-seal-replacement-in-tennessee",
      fixslugpath:
        "/fixes/transaxle-output-shaft-seal-replacement-in-tennessee",
      _title: "Transaxle Output Shaft Seal Replacement in Tennessee",
    },
    {
      state_id: "TX",
      state_name: "Texas",
      fixslug: "transaxle-output-shaft-seal-replacement-in-texas",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-texas",
      _title: "Transaxle Output Shaft Seal Replacement in Texas",
    },
    {
      state_id: "UT",
      state_name: "Utah",
      fixslug: "transaxle-output-shaft-seal-replacement-in-utah",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-utah",
      _title: "Transaxle Output Shaft Seal Replacement in Utah",
    },
    {
      state_id: "VA",
      state_name: "Virginia",
      fixslug: "transaxle-output-shaft-seal-replacement-in-virginia",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-virginia",
      _title: "Transaxle Output Shaft Seal Replacement in Virginia",
    },
    {
      state_id: "VT",
      state_name: "Vermont",
      fixslug: "transaxle-output-shaft-seal-replacement-in-vermont",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-vermont",
      _title: "Transaxle Output Shaft Seal Replacement in Vermont",
    },
    {
      state_id: "WA",
      state_name: "Washington",
      fixslug: "transaxle-output-shaft-seal-replacement-in-washington",
      fixslugpath:
        "/fixes/transaxle-output-shaft-seal-replacement-in-washington",
      _title: "Transaxle Output Shaft Seal Replacement in Washington",
    },
    {
      state_id: "WI",
      state_name: "Wisconsin",
      fixslug: "transaxle-output-shaft-seal-replacement-in-wisconsin",
      fixslugpath:
        "/fixes/transaxle-output-shaft-seal-replacement-in-wisconsin",
      _title: "Transaxle Output Shaft Seal Replacement in Wisconsin",
    },
    {
      state_id: "WV",
      state_name: "West Virginia",
      fixslug: "transaxle-output-shaft-seal-replacement-in-west-virginia",
      fixslugpath:
        "/fixes/transaxle-output-shaft-seal-replacement-in-west-virginia",
      _title: "Transaxle Output Shaft Seal Replacement in West Virginia",
    },
    {
      state_id: "WY",
      state_name: "Wyoming",
      fixslug: "transaxle-output-shaft-seal-replacement-in-wyoming",
      fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement-in-wyoming",
      _title: "Transaxle Output Shaft Seal Replacement in Wyoming",
    },
  ],

  fix: {
    fixCauseTitles: ["Transaxle Seal Leak"],
    symptomSlugs: [
      "my-car-smells-like-burning-oil-or-hot-tar-template",
      "my-car-smells-like-burning-oil-or-hot-tar-for-julio",
      "my-car-smells-like-burning-oil",
    ],
    fixTitle: "Transaxle Output Shaft Seal Replacement",
    causeTitle: "Transaxle Seal Leak",
    fixslug: "transaxle-output-shaft-seal-replacement",
    fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement",
    wo: [
      {
        _title: "Transaxle Output Shaft Seal Replacement",
        jobs: [
          {
            _val: "Left or Right Output Shaft Seal Replacement",
            val: {
              Value: "Left or Right Output Shaft Seal Replacement",
            },
          },
        ],
      },
    ],
    image: "",
    imageAltText: "",
    ranks: {
      safety: {
        _content: "",
        _tooltip: "",
        valueStr: "",
        value: 0,
      },
      cost: {
        _content:
          "<p>Oil leaking and soaking rubber and plastic components will cause damages when not corrected over a long time. </p>",
        _tooltip: "",
        valueStr: "Medium",
        value: 50,
      },
      environment: {
        _content:
          "<p>Leaking transaxle fluid leaks get built up on the garage, driveway, streets and get washed into the rivers and streams when it rains and is an environmental concern.</p>",
        _tooltip: "",
        valueStr: "Medium",
        value: 50,
      },
    },
    hasRanks: true,
    categorySlug: "uncategorized",
    categoryName: "Uncategorized",
    headerImageSrc:
      "https://dev.autotechiq.com/symptom/my-car-smells-like-burning-oil-or-hot-tar-template/files_2022_10_library-4-1024x540-1-e1667594798989.webp",
    symptomPostSlug: "my-car-smells-like-burning-oil-or-hot-tar-template",
    symptomPostName: "My Car smells like Burning Oil or Hot Tar - Template ",
  },
  fixCauseTitles: ["Transaxle Seal Leak"],
  symptomSlugs: [
    "my-car-smells-like-burning-oil-or-hot-tar-template",
    "my-car-smells-like-burning-oil-or-hot-tar-for-julio",
    "my-car-smells-like-burning-oil",
  ],
  fixslug: "transaxle-output-shaft-seal-replacement",
  fixslugpath: "/fixes/transaxle-output-shaft-seal-replacement",
  top_fix_slug: "transaxle-output-shaft-seal-replacement",
  top_fix_slug_path: "/fixes/transaxle-output-shaft-seal-replacement",
  _title: "Transaxle Output Shaft Seal Replacement",
  _full_title: "",
  parentSymptoms: [
    {
      slug: "my-car-smells-like-burning-oil-or-hot-tar-template",
      symptom: "Car smells like Burning Oil or Hot Tar - Template",
      title: "My Car smells like Burning Oil or Hot Tar - Template ",
      _menuTitle: "",
      url: "https://dev.autotechiq.com/symptom/my-car-smells-like-burning-oil-or-hot-tar-template",
      date: "7/22/2022 4:16:12 AM",
      mainImage: {
        id: 0,
        width: 0,
        height: 0,
        filesize: 0,
        url: "https://dev.autotechiq.com/symptom/my-car-smells-like-burning-oil-or-hot-tar-template/files_2022_06_smells-like-tar.webp",
        size: "",
        alt: "",
        pixels: 0,
        type: "",
      },
      mainImageType: "",
    },
    {
      slug: "my-car-smells-like-burning-oil-or-hot-tar-for-julio",
      symptom: "Car smells like Burning Oil",
      title: "My Car smells like Burning Oil",
      _menuTitle: "",
      url: "https://dev.autotechiq.com/symptom/my-car-smells-like-burning-oil-or-hot-tar-for-julio",
      date: "8/23/2022 6:09:57 PM",
      mainImage: {
        id: 0,
        width: 0,
        height: 0,
        filesize: 0,
        url: "https://dev.autotechiq.com/symptom/my-car-smells-like-burning-oil-or-hot-tar-for-julio/files_2022_06_smells-like-tar.webp",
        size: "",
        alt: "",
        pixels: 0,
        type: "",
      },
      mainImageType: "",
    },
    {
      slug: "my-car-smells-like-burning-oil",
      symptom: "Hey, Why Does My Car Smell Like Burning Oil?",
      title: "Hey, Why Does My Car Smell Like Burning Oil?",
      _menuTitle: "Burning Oil Smell",
      url: "https://dev.autotechiq.com/symptom/my-car-smells-like-burning-oil",
      date: "9/9/2022 7:57:32 PM",
      mainImage: {
        id: 0,
        width: 0,
        height: 0,
        filesize: 0,
        url: "https://dev.autotechiq.com/symptom/my-car-smells-like-burning-oil/files_2022_12_Img-2.webp",
        size: "",
        alt: "",
        pixels: 0,
        type: "",
      },
      mainImageType: "",
      _topImgCaption: "A burning oil smell can happen because of leaks",
    },
  ],
  relatedSymptoms: [
    {
      slug: "hello-world",
      symptom: "Hello world 12",
      title: "Hello world 12",
      _menuTitle: "",
      url: "https://dev.autotechiq.com/symptom/hello-world",
      date: "6/27/2022 12:38:28 AM",
      mainImage: {
        id: 0,
        width: 0,
        height: 0,
        filesize: 0,
        url: "",
        size: "",
        alt: "",
        pixels: 0,
        type: "",
      },
      mainImageType: "",
      _shortContent: "",
      _topImgCaption: "",
    },
    {
      slug: "my-car-smells-like-burning-rubber",
      symptom: "Car smells like Burning Rubber",
      title: "My Car smells like Burning Rubber",
      _menuTitle: "",
      url: "https://dev.autotechiq.com/symptom/my-car-smells-like-burning-rubber",
      date: "6/30/2022 3:38:40 PM",
      mainImage: {
        id: 0,
        width: 0,
        height: 0,
        filesize: 0,
        url: "https://dev.autotechiq.com/symptom/my-car-smells-like-burning-rubber/files_2022_06_woman-holding-nose-612x490-1.webp",
        size: "",
        alt: "",
        pixels: 0,
        type: "",
      },
      mainImageType: "",
      _shortContent:
        "<p>When it comes to your car or truck, a bad smell is not a good sign; it can come from any part of your car or truck. Whether your car smells like burning rubber when starting your car or truck or another odor,  it is challenging to identify where it comes from, especially when you start to panic about the worst possible scenario. </p>",
      _topImgCaption:
        "Regardless of how alarming you think the strange smell is, your first action should be to stop the car or truck, start finding the cause, or just drive to the nearest auto repair shop you trust, ideally within a 5-mile radius.",
    },
    {
      slug: "crackling-noise-in-car-when-engine-turned-off",
      symptom: "Crackling noise in car when engine turned off",
      title: "Crackling noise in car when engine turned off",
      _menuTitle: "",
      url: "https://dev.autotechiq.com/symptom/crackling-noise-in-car-when-engine-turned-off",
      date: "7/2/2022 11:23:52 PM",
      mainImage: {
        id: 0,
        width: 0,
        height: 0,
        filesize: 0,
        url: "https://lh4.googleusercontent.com/bfXI4_FEwlCi3hN9Emb9_1r5ts7uI_jLLW0N1Yh9co1A8B8lH8tblvrETK4l_6RZgYwS8RBzoRDpjW8LZJZm7Mr1lVQInPTIQUepVWdli8gSu8oSucfDjWGcAWErkNOL_EVvE8Uq53HoOU4vyA",
        size: "",
        alt: "",
        pixels: 0,
        type: "",
      },
      mainImageType: "",
      _shortContent:
        "<p></p><p>When it comes to your car or truck, an unusual noise is not a good sign; it can come from any part of your car or truck. Whether there is a crackling noise in your car when the engine is turned off or another sound, it is challenging to identify where it comes from, especially when you start to panic about the worst possible scenario.</p>",
      _topImgCaption:
        "Sometimes it is hard to know where the strange sounds come from. Your first action should be to stop the car or truck and find the cause. Sometimes they are obvious and can be identified as coming from areas such as the cooling fan, fuel pump, engine block, exhaust pipes, or exhaust manifolds.",
    },
    {
      slug: "my-car-smells-like-burning-rubber-2",
      symptom: "Car  smells like Burning Rubber - Template",
      title: "My Car  smells like Burning Rubber - Template ",
      _menuTitle: "",
      url: "https://dev.autotechiq.com/symptom/my-car-smells-like-burning-rubber-2",
      date: "7/19/2022 10:05:39 PM",
      mainImage: {
        id: 0,
        width: 0,
        height: 0,
        filesize: 0,
        url: "https://dev.autotechiq.com/symptom/my-car-smells-like-burning-rubber-2/files_2022_06_2022-06-29_15-19-52.webp",
        size: "",
        alt: "",
        pixels: 0,
        type: "",
      },
      mainImageType: "",
      _topImgCaption:
        "A burnt rubber smell is the second most frequent symptom. Often, it is not tire-related; the burning rubber smell coming instead from the engine or exhaust pipe. Your car or truck consists of many parts made of rubber. Examples are coolant hoses, steering hoses, the timing belt, and other accessory drive belts, which are all key components of your car or truck.",
    },
    {
      slug: "my-car-expereinces-a-symptom-keyphrase-the-article-is-optimized-for-template",
      symptom:
        "Car  [expereinces a symptom keyphrase the article is optimized for - Template]",
      title:
        "My Car  [expereinces a symptom keyphrase the article is optimized for - Template] ",
      _menuTitle: "",
      url: "https://dev.autotechiq.com/symptom/my-car-expereinces-a-symptom-keyphrase-the-article-is-optimized-for-template",
      date: "8/9/2022 12:13:53 AM",
      mainImage: {
        id: 0,
        width: 0,
        height: 0,
        filesize: 0,
        url: "https://dev.autotechiq.com/symptom/my-car-expereinces-a-symptom-keyphrase-the-article-is-optimized-for-template/files_2022_08_chuckle-image.webp",
        size: "",
        alt: "",
        pixels: 0,
        type: "",
      },
      mainImageType: "",
      _topImgCaption:
        "[Have the motorist understand through a 'teasing' explanation where the causes come from. Illustrate the potential variety of causes and whether the cause is obvious or the symptom is leading down the wrong track, ex.: burnt rubber smell not coming from the tires. ]",
    },
    {
      slug: "my-car-smells-like-rotten-eggs-template",
      symptom: "Car Smells Like Rotten Eggs - Template",
      title: "My Car Smells Like Rotten Eggs - Template ",
      _menuTitle: "",
      url: "https://dev.autotechiq.com/symptom/my-car-smells-like-rotten-eggs-template",
      date: "8/22/2022 3:35:28 PM",
      mainImage: {
        id: 0,
        width: 0,
        height: 0,
        filesize: 0,
        url: "https://dev.autotechiq.com/symptom/my-car-smells-like-rotten-eggs-template/files_2022_08_smells-like-rotten-eggs.webp",
        size: "",
        alt: "",
        pixels: 0,
        type: "",
      },
      mainImageType: "",
      _topImgCaption:
        "When your vehicle smell like rotten eggs your not alone. AutoTechIQ’s records show cars and trucks across all makes and models are prone to this foul order at times. This type of odor arises more commonly in certain driving conditions.",
    },
    {
      slug: "my-car-smells-like-burning-oil-or-hot-tar-for-julio",
      symptom: "Car smells like Burning Oil",
      title: "My Car smells like Burning Oil",
      _menuTitle: "",
      url: "https://dev.autotechiq.com/symptom/my-car-smells-like-burning-oil-or-hot-tar-for-julio",
      date: "8/23/2022 6:09:57 PM",
      mainImage: {
        id: 0,
        width: 0,
        height: 0,
        filesize: 0,
        url: "https://dev.autotechiq.com/symptom/my-car-smells-like-burning-oil-or-hot-tar-for-julio/files_2022_06_smells-like-tar.webp",
        size: "",
        alt: "",
        pixels: 0,
        type: "",
      },
      mainImageType: "",
      _topImgCaption:
        "AutoTechIQ's records show that a hot tar or burning oil smell appears across all makes and models.",
    },
    {
      slug: "my-car-smells-like-burning-plastic-template",
      symptom: "Car Smells Like Burning Plastic - Template",
      title: "My Car Smells Like Burning Plastic - Template ",
      _menuTitle: "",
      url: "https://dev.autotechiq.com/symptom/my-car-smells-like-burning-plastic-template",
      date: "9/6/2022 3:21:37 PM",
      mainImage: {
        id: 0,
        width: 0,
        height: 0,
        filesize: 0,
        url: "https://dev.autotechiq.com/symptom/my-car-smells-like-burning-plastic-template/files_2022_06_woman-holding-nose-612x490-1.webp",
        size: "",
        alt: "",
        pixels: 0,
        type: "",
      },
      mainImageType: "",
      _topImgCaption:
        "Burning plastic smells can have many different causes. While all the symptoms can seen the same. A few of the causes can be easy fixes you can perform yourself.",
    },
    {
      slug: "hello-world",
      symptom: "Hello world 12",
      title: "Hello world 12",
      _menuTitle: "",
      url: "https://dev.autotechiq.com/symptom/hello-world",
      date: "6/27/2022 12:38:28 AM",
      mainImage: {
        id: 0,
        width: 0,
        height: 0,
        filesize: 0,
        url: "",
        size: "",
        alt: "",
        pixels: 0,
        type: "",
      },
      mainImageType: "",
      _shortContent: "",
      _topImgCaption: "",
    },
    {
      slug: "my-car-smells-like-burning-rubber",
      symptom: "Car smells like Burning Rubber",
      title: "My Car smells like Burning Rubber",
      _menuTitle: "",
      url: "https://dev.autotechiq.com/symptom/my-car-smells-like-burning-rubber",
      date: "6/30/2022 3:38:40 PM",
      mainImage: {
        id: 0,
        width: 0,
        height: 0,
        filesize: 0,
        url: "https://dev.autotechiq.com/symptom/my-car-smells-like-burning-rubber/files_2022_06_woman-holding-nose-612x490-1.webp",
        size: "",
        alt: "",
        pixels: 0,
        type: "",
      },
      mainImageType: "",
      _topImgCaption:
        "Regardless of how alarming you think the strange smell is, your first action should be to stop the car or truck, start finding the cause, or just drive to the nearest auto repair shop you trust, ideally within a 5-mile radius.",
    },
    {
      slug: "crackling-noise-in-car-when-engine-turned-off",
      symptom: "Crackling noise in car when engine turned off",
      title: "Crackling noise in car when engine turned off",
      _menuTitle: "",
      url: "https://dev.autotechiq.com/symptom/crackling-noise-in-car-when-engine-turned-off",
      date: "7/2/2022 11:23:52 PM",
      mainImage: {
        id: 0,
        width: 0,
        height: 0,
        filesize: 0,
        url: "https://lh4.googleusercontent.com/bfXI4_FEwlCi3hN9Emb9_1r5ts7uI_jLLW0N1Yh9co1A8B8lH8tblvrETK4l_6RZgYwS8RBzoRDpjW8LZJZm7Mr1lVQInPTIQUepVWdli8gSu8oSucfDjWGcAWErkNOL_EVvE8Uq53HoOU4vyA",
        size: "",
        alt: "",
        pixels: 0,
        type: "",
      },
      mainImageType: "",
      _topImgCaption:
        "Sometimes it is hard to know where the strange sounds come from. Your first action should be to stop the car or truck and find the cause. Sometimes they are obvious and can be identified as coming from areas such as the cooling fan, fuel pump, engine block, exhaust pipes, or exhaust manifolds.",
    },
    {
      slug: "my-car-smells-like-burning-rubber-2",
      symptom: "Car  smells like Burning Rubber - Template",
      title: "My Car  smells like Burning Rubber - Template ",
      _menuTitle: "",
      url: "https://dev.autotechiq.com/symptom/my-car-smells-like-burning-rubber-2",
      date: "7/19/2022 10:05:39 PM",
      mainImage: {
        id: 0,
        width: 0,
        height: 0,
        filesize: 0,
        url: "https://dev.autotechiq.com/symptom/my-car-smells-like-burning-rubber-2/files_2022_06_2022-06-29_15-19-52.webp",
        size: "",
        alt: "",
        pixels: 0,
        type: "",
      },
      mainImageType: "",
      _topImgCaption:
        "A burnt rubber smell is the second most frequent symptom. Often, it is not tire-related; the burning rubber smell coming instead from the engine or exhaust pipe. Your car or truck consists of many parts made of rubber. Examples are coolant hoses, steering hoses, the timing belt, and other accessory drive belts, which are all key components of your car or truck.",
    },
    {
      slug: "my-car-smells-like-burning-oil-or-hot-tar-template",
      symptom: "Car smells like Burning Oil or Hot Tar - Template",
      title: "My Car smells like Burning Oil or Hot Tar - Template ",
      _menuTitle: "",
      url: "https://dev.autotechiq.com/symptom/my-car-smells-like-burning-oil-or-hot-tar-template",
      date: "7/22/2022 4:16:12 AM",
      mainImage: {
        id: 0,
        width: 0,
        height: 0,
        filesize: 0,
        url: "https://dev.autotechiq.com/symptom/my-car-smells-like-burning-oil-or-hot-tar-template/files_2022_06_smells-like-tar.webp",
        size: "",
        alt: "",
        pixels: 0,
        type: "",
      },
      mainImageType: "",
      _topImgCaption:
        "AutoTechIQ’s records show that smells like burning oil or hot tar are the most common issue across all makes and models. If you have walked or driven by a site where asphalt is applied, you know how strong that odor can be.",
    },
    {
      slug: "my-car-expereinces-a-symptom-keyphrase-the-article-is-optimized-for-template",
      symptom:
        "Car  [expereinces a symptom keyphrase the article is optimized for - Template]",
      title:
        "My Car  [expereinces a symptom keyphrase the article is optimized for - Template] ",
      _menuTitle: "",
      url: "https://dev.autotechiq.com/symptom/my-car-expereinces-a-symptom-keyphrase-the-article-is-optimized-for-template",
      date: "8/9/2022 12:13:53 AM",
      mainImage: {
        id: 0,
        width: 0,
        height: 0,
        filesize: 0,
        url: "https://dev.autotechiq.com/symptom/my-car-expereinces-a-symptom-keyphrase-the-article-is-optimized-for-template/files_2022_08_chuckle-image.webp",
        size: "",
        alt: "",
        pixels: 0,
        type: "",
      },
      mainImageType: "",
      _topImgCaption:
        "[Have the motorist understand through a 'teasing' explanation where the causes come from. Illustrate the potential variety of causes and whether the cause is obvious or the symptom is leading down the wrong track, ex.: burnt rubber smell not coming from the tires. ]",
    },
    {
      slug: "my-car-smells-like-rotten-eggs-template",
      symptom: "Car Smells Like Rotten Eggs - Template",
      title: "My Car Smells Like Rotten Eggs - Template ",
      _menuTitle: "",
      url: "https://dev.autotechiq.com/symptom/my-car-smells-like-rotten-eggs-template",
      date: "8/22/2022 3:35:28 PM",
      mainImage: {
        id: 0,
        width: 0,
        height: 0,
        filesize: 0,
        url: "https://dev.autotechiq.com/symptom/my-car-smells-like-rotten-eggs-template/files_2022_08_smells-like-rotten-eggs.webp",
        size: "",
        alt: "",
        pixels: 0,
        type: "",
      },
      mainImageType: "",
      _topImgCaption:
        "When your vehicle smell like rotten eggs your not alone. AutoTechIQ’s records show cars and trucks across all makes and models are prone to this foul order at times. This type of odor arises more commonly in certain driving conditions.",
    },
    {
      slug: "my-car-smells-like-burning-plastic-template",
      symptom: "Car Smells Like Burning Plastic - Template",
      title: "My Car Smells Like Burning Plastic - Template ",
      _menuTitle: "",
      url: "https://dev.autotechiq.com/symptom/my-car-smells-like-burning-plastic-template",
      date: "9/6/2022 3:21:37 PM",
      mainImage: {
        id: 0,
        width: 0,
        height: 0,
        filesize: 0,
        url: "https://dev.autotechiq.com/symptom/my-car-smells-like-burning-plastic-template/files_2022_06_woman-holding-nose-612x490-1.webp",
        size: "",
        alt: "",
        pixels: 0,
        type: "",
      },
      mainImageType: "",
    },
    {
      slug: "my-car-smells-like-burning-rubber-3",
      symptom: "Hey, Why Does My Car  Smell Like Burning Rubber?",
      title: "Hey, Why Does My Car  Smell Like Burning Rubber?",
      _menuTitle: "Burning Rubber Smell",
      url: "https://dev.autotechiq.com/symptom/my-car-smells-like-burning-rubber-3",
      date: "9/11/2022 4:41:21 PM",
      mainImage: {
        id: 0,
        width: 0,
        height: 0,
        filesize: 0,
        url: "https://dev.autotechiq.com/symptom/my-car-smells-like-burning-rubber-3/files_2022_06_2022-06-29_15-19-52.webp",
        size: "",
        alt: "",
        pixels: 0,
        type: "",
      },
      mainImageType: "",
      _shortContent:
        "<p>Burning rubber smells can be from slipping car belts, broken tensioners, and more. We’ll give you expert advice on that.</p>",
      _topImgCaption: "The smell of burning rubber is very distinct.",
    },
    {
      slug: "my-car-smells-like-rotten-eggs",
      symptom: "Hey, Why Does My Car Smell Like Rotten Eggs?",
      title: "Hey, Why Does My Car Smell Like Rotten Eggs?",
      _menuTitle: "Rotten Egg Smell",
      url: "https://dev.autotechiq.com/symptom/my-car-smells-like-rotten-eggs",
      date: "9/11/2022 5:36:00 PM",
      mainImage: {
        id: 0,
        width: 0,
        height: 0,
        filesize: 0,
        url: "https://dev.autotechiq.com/symptom/my-car-smells-like-rotten-eggs/files_2022_08_smells-like-rotten-eggs.webp",
        size: "",
        alt: "",
        pixels: 0,
        type: "",
      },
      mainImageType: "",
    },
    {
      slug: "my-car-smells-like-burning-plastic",
      symptom: "Hey, Why Does My Car Smell Like Burning Plastic?",
      title: "Hey, Why Does My Car Smell Like Burning Plastic?",
      _menuTitle: "Burning Plastic Smell",
      url: "https://dev.autotechiq.com/symptom/my-car-smells-like-burning-plastic",
      date: "9/13/2022 6:45:01 PM",
      mainImage: {
        id: 0,
        width: 0,
        height: 0,
        filesize: 0,
        url: "https://dev.autotechiq.com/symptom/my-car-smells-like-burning-plastic/files_2022_09_img_0024.webp",
        size: "",
        alt: "",
        pixels: 0,
        type: "",
      },
      mainImageType: "",
      _shortContent:
        "<p>Burning plastic smells can be from stuck plastic debris to electrical issues. Our experts will guide you on what to do.</p>",
      _topImgCaption: "",
    },
  ],
};
